//! System clipboard via `arboard`, plus the per-OS pieces arboard does not
//! offer: a cheap change token and the "this is a secret" marker.

use super::{BackendError, ClipContent, ClipboardBackend};
use crate::clipboard::{decode_png_rgba, encode_png_rgba};

pub struct SystemClipboard {
    cb: arboard::Clipboard,
}

impl SystemClipboard {
    pub fn new() -> Result<Self, BackendError> {
        arboard::Clipboard::new().map(|cb| Self { cb }).map_err(|e| BackendError::Unavailable(format!("clipboard unavailable: {e}")))
    }
}

#[cfg(target_os = "macos")]
fn token() -> Option<u64> {
    Some(objc2_app_kit::NSPasteboard::generalPasteboard().changeCount() as u64)
}

#[cfg(target_os = "macos")]
fn sensitive() -> bool {
    // Password managers mark what they put on the pasteboard with these types.
    let pb = objc2_app_kit::NSPasteboard::generalPasteboard();
    pb.types().is_some_and(|types| {
        types.iter().any(|t| {
            let s = t.to_string();
            s == "org.nspasteboard.ConcealedType" || s == "org.nspasteboard.TransientType" || s == "org.nspasteboard.AutoGeneratedType"
        })
    })
}

#[cfg(target_os = "windows")]
fn token() -> Option<u64> {
    // SAFETY: argument-free Win32 call returning a counter.
    Some(unsafe { windows_sys::Win32::System::DataExchange::GetClipboardSequenceNumber() } as u64)
}

#[cfg(target_os = "windows")]
fn sensitive() -> bool {
    use windows_sys::Win32::System::DataExchange::{IsClipboardFormatAvailable, RegisterClipboardFormatW};
    let name: Vec<u16> = "ExcludeClipboardContentFromMonitorProcessing\0".encode_utf16().collect();
    // SAFETY: `name` is a valid NUL-terminated UTF-16 string that outlives both calls.
    unsafe {
        let fmt = RegisterClipboardFormatW(name.as_ptr());
        fmt != 0 && IsClipboardFormatAvailable(fmt) != 0
    }
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn token() -> Option<u64> {
    None
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn sensitive() -> bool {
    false
}

impl ClipboardBackend for SystemClipboard {
    fn change_token(&mut self) -> Option<u64> {
        token()
    }

    fn read(&mut self) -> Result<Option<ClipContent>, BackendError> {
        match self.cb.get_text() {
            Ok(t) if !t.is_empty() => return Ok(Some(ClipContent::Text(t))),
            Ok(_) | Err(arboard::Error::ContentNotAvailable) => {}
            Err(e) => return Err(BackendError::Failed(format!("clipboard read: {e}"))),
        }
        match self.cb.get_image() {
            Ok(img) => encode_png_rgba(img.width as u32, img.height as u32, &img.bytes).map(|p| Some(ClipContent::Image(p))).map_err(BackendError::Failed),
            Err(arboard::Error::ContentNotAvailable) => Ok(None),
            Err(e) => Err(BackendError::Failed(format!("clipboard read: {e}"))),
        }
    }

    fn write(&mut self, c: &ClipContent) -> Result<Option<u64>, BackendError> {
        match c {
            ClipContent::Text(t) => self.cb.set_text(t.clone()).map_err(|e| BackendError::Failed(format!("clipboard write: {e}")))?,
            ClipContent::Image(png) => {
                let (w, h, rgba) = decode_png_rgba(png).map_err(BackendError::Failed)?;
                self.cb
                    .set_image(arboard::ImageData { width: w as usize, height: h as usize, bytes: rgba.into() })
                    .map_err(|e| BackendError::Failed(format!("clipboard write: {e}")))?;
            }
        }
        Ok(token())
    }

    fn is_sensitive(&mut self) -> bool {
        sensitive()
    }
}
